// ------ Transaction api ------

### Get Transaction
GET http://localhost:8081/api/v2/transaction HTTP/1.1
Content-Type: application/json

### Create Transaction
POST http://localhost:8081/api/v2/transaction HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjIyNjAxOTQsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoia2Fyb29uIn0.9_g27K1ZEOnGDqtZ98_VyRUyrtXj3kuTJ-iLX_IaYcU 
Content-Type: application/json

{
    "total":50.50,
    "paid":100,
    "change":49.50,
    "payment_type":"cash",
    "payment_detail":"full",
    "order_list":"[]"
}


