// ------ Transaction api ------

### Get Transaction
GET http://localhost:8081/api/v2/transaction HTTP/1.1
Content-Type: application/json

### Create Transaction
POST http://localhost:8081/api/v2/transaction HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjI0MzI3NzQsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoia2Fyb29uIn0.aek2gz0dzl4kLeUcG4r91Y52NOgVE90MHwW-sa8IShU
Content-Type: application/json

{
    "total":50.50,
    "paid":100,
    "change":49.50,
    "payment_type":"cash",
    "payment_detail":"full",
    "order_list":"[]"
}


